
name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install libraries
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake libgmp-dev libmpfr-dev libboost-all-dev gringo python3-pip

      - name: Install gringo
        run: |
          pip install networkx

      - name: Download normalization
        run: |
          wget https://research.ics.aalto.fi/software/asp/lp2normal/binary-x86-64/lp2normal-2.27
          chmod +x lp2normal-2.27

      - name: Run build
        run: |
          chmod +x build.sh
          ./build.sh
          
      - name: Sample SharpASP (std) Run
        run: |
          python run-sharpasp.py -i graph_reach.random-graph-20-3-5.zip.lp -c std | tee /tmp/out.txt
          grep -q "SharpASP Count: 99086" /tmp/out.txt

      - name: Sample SharpASP (ganak) Run
        run: |
          python run-sharpasp.py -i graph_reach.random-graph-20-3-5.zip.lp -c ganak | tee /tmp/out.txt
          grep -q "SharpASP Count: 99086" /tmp/out.txt

      - name: Sample SharpASP (d4) Run
        run: |
          python run-sharpasp.py -i graph_reach.random-graph-20-3-5.zip.lp -c d4 | tee /tmp/out.txt
          grep -q "SharpASP Count: 99086" /tmp/out.txt